### ISSUE TITLE
Is this still in development?

### ISSUE THREAD

**Issue by chevex** [ajaxorg/cloud9#3239]
I noticed there haven't been any commits to this repository since November of last year. Is this project still in development?

**Comment by nerdev** [comment]
looking for an update to v3 as well. I have tried out the free version at c9.io and the v2 version here and  v3 does seem to run more smoothe. I know developers aren't too keen on setting release dates, but can you tell us a month, or even what quarter you expect to update the repository to v3? I would really appreciate something. I also wanted to say thank you to you and everyone else who has contributed to c9, its a great project!

**Comment by portokallidis** [comment]
It seems [waiting makes us happy](http://time.com/3182382/why-waiting-actually-makes-you-happy/)! tick tock

**Comment by lucamilanesio** [comment]
Any news on c9 v3 OpenSource? ... early January is here :smile:

**Comment by javruben** [comment]
https://github.com/ajaxorg/cloud9/issues/3200#issuecomment-68638466

**Comment by John-Appleseed** [comment]
Cloud9 is a confusing service. Is this product open source or not? I'm boycotting c9 until the Cloud9 executives grew a brain about of how to support an open source community *#@! truly this is damaging your  __customer relationship__  to __open source community__. You've been braindead for a year. 

**Let us patch you up**!




Discourse.org is smart product model to follow. They are able to keep an active open source community while making money from their hosted services, like you already do. 

Braindead ridiculous

**Comment by chevex** [comment]
I think that's a little harsh dude. I agree that I think it's a weird decision to completely avoid community contributions in a supposedly open-source project, but you don't have to act like a child.

**Comment by John-Appleseed** [comment]
I feel rejected. Where do I go to help Cloud9? Apparently we the contributes are seen as lesser individuals to help an awesome tool.

Love you project, but you guys have some problems.

**Comment by oliverseal** [comment]
+1 @chevex

**Comment by John-Appleseed** [comment]
Ok. Cloud9 can do whatever they want and treat the community however they please. So luckily invisible hand has shown me a working __open source community__ of cloud9 at https://www.codebox.io

Sorry for me being a die hard open source supporter.  I believe in contribution and avoid greedy/confusing organizations. I would like to call this common sense but some might not agree.

Moving on.

**Comment by chevex** [comment]
Try not to cry too much, and don't let the door hit you on the way out.

**Comment by javruben** [comment]
Hey guys, I see there's a lot of emotion in this thread. I understand the frustration and for that I apologize. I'll write a longer blog post when we release the SDK to dive deeper into the decisions we made in order to get to a product that you now all would like to see open sourced.

I understand that the wait is too long for some of you and that you question some of our decisions, especially not having all the context. I respect that and hope to make that right in a few weeks when we release our SDK.
