### ISSUE TITLE
git config --global core.editor "cloud9/ace" ??

### ISSUE THREAD

**Issue by TurkeyJerky** [ajaxorg/cloud9#3248]
Hello,
I am taking a class at udacity about git and github. In a part of the class we configure our workspace a bit and we set our global editor to be sublime. What should I type to make this work with my cloud9 IDE?

Thanks in advance.
Happy new year!

**Comment by Pike** [comment]
I guess this would be easy if we had a solution for #2698.

**Comment by javruben** [comment]
Indeed. We have a solution for it but removed because of for some unrelated security concerns. With the release of the SDK in January we'll redeploy the c9 cli which will enable this.

**Comment by TurkeyJerky** [comment]
Ok glad to hear it. Thank you very much :)
