### ISSUE TITLE
Cloud 9 IDE - Asterisk for uncommited changes in command prompt

### ISSUE THREAD

**Issue by TurkeyJerky** [ajaxorg/cloud9#3249]
I want to use a feature to show an asterisk in my command prompt whenever my commit is dirty(I've made uncommited changes). I've searched in google, cloud9 guides etc but didn't find anything for cloud9 spcifically. What I did was to change my .bashrc file in my cloud9 account. I tried 2 solutions that I found through google and none of them worked.

What is the proper way to do such a thing?
Thanks

**Comment by higginsrob** [comment]
You need to delete or comment out a line in your default cloud 9 .bashrc that sets your PS1 prompt, so 

`#PS1='\[\033[01;32m\]${C9_USER}@${C9_PROJECT}\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(__git_ps1 " (%s)") $ '`

I then put all my alias and prompt logic in the .bash_aliases file.  This makes starting new projects as easy as commenting out one line in .bashrc and completely replace .bash_aliases with a copy/paste.  I wrote a [.bash_aliases gist for use with cloud 9 nodejs/mongodb projects](https://gist.github.com/higginsrob/d9bd8d4461fc1cfe33a2).  It will color your prompt, show the current branch, and color the branch red if the commit is dirty.

**Comment by TurkeyJerky** [comment]
Just to be clear. Do I have to do this for every project I am creating in cloud9? Is there any way around it?

**Comment by higginsrob** [comment]
Yes, you will need to do this for every project.  Learning how to use a bash shell can be daunting at first but is a powerful tool as a developer.  Cloud9 did a great job on their command line interface, their streaming cli emulation is almost as fast and just as useful as a local terminal.  .bashrc is just your config file for bash and will run every time you start a new terminal.  The default cloud9 .bashrc runs .bash_aliases for you, that file is not standard in all bash/ssh consoles.

**Comment by TurkeyJerky** [comment]
Editing bash is not my problem :) I wish I could do universla default changes that's all!
You've been very helpful though.
Thanks a lot.
Happy new year :)

**Comment by javruben** [comment]
Cloud9 has an 'init script' feature. This script is called when the IDE starts. You also have access to all the plugins. You could create a small script that checks if your .bashrc is there and if it's not write it. You can edit your script via the Cloud9 menu. Cloud9 > Open Your Init Script.

A script would look like this:
```
services.fs.exists("~/.bashrc", function(exists){
    if (!exists) {
        fs.writeFile("~/.bashrc". "CONTENT", function(err){
            if (err) console.log(err);
        });
    }
}
```

**Comment by javruben** [comment]
Full docs for the plugins are there: https://docs.c9.io/api

**Comment by TurkeyJerky** [comment]
Thanks a lot javruben, I'll take a look. :)

**Comment by higginsrob** [comment]
Hey TurkeyJerky,  I hadn't felt like setting up new dev boxes was much work on c9, but after creating and deleting a few repos today I decided to take a look at the init script.  The code below checks for the presences of the file '~/.init_c9_aliases', and if not found it will download my gist of bash aliases, write them into ~/.bash_aliases, and then write the file ~/.init_c9_aliases so that it won't execute again next time you load the project.

```
// You can access plugins via the "services" global variable
/*global services*/

services.fs.exists("~/.init_c9_aliases", function(exists){
  if(!exists){
    services.http.request("https://gist.githubusercontent.com/higginsrob/d9bd8d4461fc1cfe33a2/raw/0e037dd946ac2da198f807d93b88ead6a381a6bd/.bash_aliases",
      function(err, data) {
        if(err)return console.log(err);
        services.fs.writeFile("~/.bash_aliases", data, function(err){
          if(err)return console.log(err);
          services.fs.writeFile("~/.init_c9_aliases", 'aliases have been installed from gist: https://gist.github.com/higginsrob/d9bd8d4461fc1cfe33a2', function(err){
            if(err)console.log(err);
          });
        });
      }
    );
  }
});
```
