### ISSUE TITLE
how to release project that go to hibernate mode

### ISSUE THREAD

**Issue by NivTi** [ajaxorg/cloud9#3251]
Hello,
i need my code from my workspace but it is in hibernate mode, how i can release it? what i need to do?

please it is very important to me :(

thanks.

**Comment by javruben** [comment]
Hi, were you helped on twitter? If not, please let me know your username and workspace name.

**Comment by NivTi** [comment]
No , I send message to support and they told me that now everything work(few hours ago) but still same problem..
Username:cookandfeed@gmail.com
Workspace: ttteesss

Thanks a lot for the fast responding!

נשלח מה-iPhone שלי

‫ב-9 בינו׳ 2015, בשעה 21:34, ‏‏Ruben Daniels ‏<notifications@github.com> כתב/ה:‬

**Comment by javruben** [comment]
Please try again.

**Comment by NivTi** [comment]
wow! thanks!!!!!!!!!!!
