### ISSUE TITLE
cloud9 v3 coming soon ?

### ISSUE THREAD

**Issue by mc007** [ajaxorg/cloud9#3256]
Hi,
2 years passed now and we're wondering this is ever going to happen at all? Could leave please a little statement about here? We've put lots of efforts in a c9 fork (very custom) and would love to know its better to switch to something else since there is no progress anymore. 

Thank you!

**Comment by chasedevelopment** [comment]
Hello Mc007,

Ceck out this threat: https://github.com/ajaxorg/cloud9/issues/3200 . They promissed we could expect v3 early this week!

Kind regards,
Nick

**Comment by mc007** [comment]
you guys rock ! thank you !
