### ISSUE TITLE
Broken c9.io Support Link in the README

### ISSUE THREAD

**Issue by carlsmith** [ajaxorg/cloud9#3257]
At the very top of the README, it says...

> If you have questions regarding the hosted service at c9.io including issues with accounts or payments, please file them at support.c9.io rather than as a GitHub issue in this repository.

The link, `support.c9.io`, goes to `https://c9.io/support/home`, which is broken. That page just says `Cannot GET /support/home`.

**Comment by carlsmith** [comment]
Does anyone have links to support or discussions, maybe a mailing list? Where do you go to ask about the hosted service?

**Comment by nightwing** [comment]
I've Fixed readme link in https://github.com/ajaxorg/cloud9/commit/8ef5642b528846a6e0e455b0d2dd9ddeaa2c4747. Thank you for reporting the issue!
Also you can send support requests from the help menu in the ide.

**Comment by carlsmith** [comment]
No problem, and thank you.
